"use client";

import React from "react";
import { Card } from "@/components/ui/zentinel-card";
import { SeverityBadge } from "@/components/ui/severity-badge";
import { Button } from "@/components/ui/button";
import { Tag } from "@/components/ui/tag";
import { AgentDot } from "@/components/ui/agent-dot";
import { Search, Filter, GitPullRequest, GitMerge, ExternalLink, X } from "lucide-react";

// Mock Data
const mockPRs = [
    {
        id: "PR-442",
        title: "fix: replace hardcoded AWS keys with environment variables",
        repo: "usestrix/core",
        vuln: "Exposed AWS Access Key",
        severity: "critical",
        status: "open",
        created: "2 hours ago",
        agent: "fix"
    },
    {
        id: "PR-440",
        title: "patch: sanitize input for `/search` q parameter",
        repo: "usestrix/frontend",
        vuln: "Reflected XSS",
        severity: "medium",
        status: "merged",
        created: "1 day ago",
        agent: "fix"
    },
    {
        id: "PR-439",
        title: "sec: enforce authorization checks on billing endpoint",
        repo: "usestrix/api",
        vuln: "Insecure Direct Object Reference (IDOR)",
        severity: "high",
        status: "merged",
        created: "3 days ago",
        agent: "fix"
    },
    {
        id: "PR-431",
        title: "bump: update python urllib3 to 2.0.7",
        repo: "usestrix/core",
        vuln: "CVE-2023-43804",
        severity: "low",
        status: "closed",
        created: "1 week ago",
        agent: "fix"
    }
];

export default function AutoFixPRsPage() {
    return (
        <div className="space-y-6">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4">
                <div>
                    <h1 className="text-3xl font-syne font-bold tracking-tight">Auto-Fix PRs</h1>
                    <p className="text-[var(--color-textSecondary)] mt-1 font-mono text-sm">Review, approve, and merge code patches generated by Fix-δ.</p>
                </div>
            </div>

            <Card className="p-0 overflow-hidden">
                <div className="p-6 border-b border-[var(--color-border)] flex flex-col sm:flex-row justify-between items-center gap-4">
                    <div className="flex items-center gap-4 w-full sm:w-auto">
                        <div className="flex items-center gap-2 text-sm font-medium">
                            <span className="text-[var(--color-textPrimary)]">All PRs (24)</span>
                            <span className="text-[var(--color-textMuted)] px-2">|</span>
                            <span className="text-[var(--color-green)] flex items-center gap-1"><GitPullRequest className="h-3.5 w-3.5" /> Open (1)</span>
                        </div>
                    </div>
                    <div className="flex items-center gap-3 w-full sm:w-auto">
                        <div className="relative flex-1 sm:w-64">
                            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-[var(--color-textMuted)]" />
                            <input
                                type="text"
                                placeholder="Search pull requests..."
                                className="w-full bg-[var(--background)] border border-[var(--color-border)] rounded-md pl-9 pr-4 py-2 text-sm focus:outline-none focus:border-[var(--color-cyan)] text-[var(--color-textPrimary)]"
                            />
                        </div>
                        <Button variant="outline" size="icon" className="border-[var(--color-border)] hover:bg-white/5">
                            <Filter className="h-4 w-4 text-[var(--color-textSecondary)]" />
                        </Button>
                    </div>
                </div>

                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="border-b border-[var(--color-border)] bg-[var(--background)]">
                                <th className="px-6 py-4 text-xs font-mono text-[var(--color-textMuted)] uppercase tracking-wider font-semibold w-2/5">Pull Request</th>
                                <th className="px-6 py-4 text-xs font-mono text-[var(--color-textMuted)] uppercase tracking-wider font-semibold">Repository</th>
                                <th className="px-6 py-4 text-xs font-mono text-[var(--color-textMuted)] uppercase tracking-wider font-semibold">Vulnerability Fixed</th>
                                <th className="px-6 py-4 text-xs font-mono text-[var(--color-textMuted)] uppercase tracking-wider font-semibold">Status</th>
                                <th className="px-6 py-4 text-xs font-mono text-[var(--color-textMuted)] uppercase tracking-wider font-semibold text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-[var(--color-border)]">
                            {mockPRs.map((pr) => (
                                <tr key={pr.id} className="hover:bg-white/5 transition-colors group">
                                    <td className="px-6 py-4">
                                        <div className="flex flex-col">
                                            <div className="flex items-center gap-2">
                                                {pr.status === "open" && <GitPullRequest className="h-4 w-4 text-[var(--color-green)]" />}
                                                {pr.status === "merged" && <GitMerge className="h-4 w-4 text-[var(--color-purple)]" />}
                                                {pr.status === "closed" && <X className="h-4 w-4 text-[var(--color-red)]" />}
                                                <span className="text-sm font-bold text-[var(--color-textPrimary)]">{pr.title}</span>
                                            </div>
                                            <div className="flex items-center gap-2 mt-1.5 ml-6">
                                                <span className="font-mono text-xs text-[var(--color-textMuted)]">{pr.id}</span>
                                                <span className="text-xs text-[var(--color-textMuted)]">· created {pr.created} by</span>
                                                <AgentDot type={pr.agent as any} animate={false} className="h-1.5 w-1.5" />
                                                <span className="font-mono text-xs text-[var(--color-cyan)]">Fix-δ</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div className="flex items-center gap-2">
                                            <span className="font-mono text-xs text-[var(--color-textSecondary)] px-2 py-1 bg-[var(--color-bgCard)] border border-[var(--color-border)] rounded-md">
                                                {pr.repo}
                                            </span>
                                        </div>
                                    </td>
                                    <td className="px-6 py-4">
                                        <div className="flex flex-col gap-1 items-start">
                                            <span className="text-sm text-[var(--color-textPrimary)]">{pr.vuln}</span>
                                            <SeverityBadge severity={pr.severity as any} className="scale-90 origin-left" />
                                        </div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        {pr.status === "open" && <Tag color="green">OPEN</Tag>}
                                        {pr.status === "merged" && <Tag color="purple">MERGED</Tag>}
                                        {pr.status === "closed" && <Tag color="red">CLOSED</Tag>}
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-right">
                                        <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <Button variant="ghost" size="sm" className="h-8 text-xs hover:bg-white/10">
                                                <ExternalLink className="h-3 w-3 mr-2" /> View diff
                                            </Button>
                                            {pr.status === "open" ? (
                                                <Button size="sm" className="h-8 text-xs bg-[var(--color-green)] text-[var(--background)] hover:bg-[var(--color-green)]/90 font-bold">
                                                    Merge PR
                                                </Button>
                                            ) : null}
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </Card>
        </div>
    );
}
