export default function TermsPage() {
    return (
        <main className="min-h-screen bg-black text-white selection:bg-[var(--color-cyan)]/30 selection:text-[var(--color-cyan)]">
            <div className="max-w-4xl mx-auto px-6 py-24 selection:bg-[var(--color-cyan)]/30">
                {/* Header Section */}
                <div className="mb-16 border-b border-white/10 pb-12">
                    <h1 className="text-5xl font-syne font-bold mb-6 tracking-tight text-white">
                        Terms of Service
                    </h1>
                    <div className="flex flex-wrap gap-6 text-[10px] font-mono uppercase tracking-[0.2em] text-[#666]">
                        <p>Effective Date: <span className="text-white">March 9, 2026</span></p>
                        <p>Version: <span className="text-white">1.3 (Public Release)</span></p>
                    </div>
                </div>

                {/* Legacy Content */}
                <div className="prose prose-invert prose-sm max-w-none space-y-12 text-[#888] font-body leading-relaxed">
                    <section className="space-y-4">
                        <p className="text-white font-medium leading-loose italic">
                            These Terms of Service (&quot;Terms&quot;, &quot;Agreement&quot;) constitute a legally binding agreement between Moyopal Ltd (trading as &quot;Zentinel&quot;) and the individual or entity (&quot;User&quot;, &quot;you&quot;, &quot;your&quot;) accessing or using the Zentinel automated security testing platform, including all associated software, APIs, autonomous agents, remediation tools, and related services (collectively, the &quot;Service&quot;).
                        </p>
                        <div className="p-6 bg-white/5 border border-white/10 rounded-xl">
                            <p className="text-white font-bold text-xs font-mono tracking-widest uppercase mb-0">
                                BY ACCESSING OR USING THE SERVICE, YOU CONFIRM THAT YOU HAVE READ, UNDERSTOOD, AND AGREED TO BE BOUND BY THESE TERMS IN THEIR ENTIRETY. IF YOU DO NOT AGREE, YOU MUST NOT ACCESS OR USE THE SERVICE.
                            </p>
                        </div>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">01.</span> DEFINITIONS
                        </h2>
                        <ul className="space-y-3 list-none pl-0">
                            <li className="flex gap-4"><span className="text-white font-bold min-w-[120px]">&quot;Service&quot;</span> <span>means the Zentinel security platform, including autonomous testing agents, CI/CD integrations, API scanners, and AI-driven remediation tools.</span></li>
                            <li className="flex gap-4"><span className="text-white font-bold min-w-[120px]">&quot;Target System&quot;</span> <span>means any domain, IP, application, or cloud infrastructure submitted by the User for testing.</span></li>
                            <li className="flex gap-4"><span className="text-white font-bold min-w-[120px]">&quot;User Data&quot;</span> <span>means any data, code, or information submitted or generated by the User (including source code snippets and vulnerability findings).</span></li>
                            <li className="flex gap-4"><span className="text-white font-bold min-w-[200px] font-syne">&quot;Remediation Suggestions&quot;</span> <span>means any AI-generated code patches, pull requests, or fix recommendations provided by the Service.</span></li>
                        </ul>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">02.</span> ELIGIBILITY AND ACCOUNT SECURITY
                        </h2>
                        <p>
                            The Service is intended for commercial and professional use. You represent that you are at least 18 years old and have the authority to bind your organization. You are solely responsible for all activity occurring under your account credentials. You must notify Zentinel immediately at <a href="mailto:legal@moyopal.io" className="text-[var(--color-cyan)] hover:underline">legal@moyopal.io</a> of any unauthorized access.
                        </p>
                    </section>

                    <section className="space-y-6 p-8 bg-[var(--color-cyan)]/5 border border-[var(--color-cyan)]/20 rounded-2xl relative overflow-hidden group">
                        <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
                            <span className="text-8xl font-black font-syne leading-none select-none">!</span>
                        </div>
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">03.</span> MANDATORY AUTHORIZATION WARRANTY
                        </h2>
                        <div className="space-y-4 relative z-10">
                            <p><strong className="text-white">3.1 Authorization Requirement.</strong> You represent and warrant that you have obtained explicit, prior, written authorization from the lawful owner of any Target System you submit to the Service. Unauthorized security testing is a violation of international law, including the U.S. Computer Fraud and Abuse Act (CFAA) and the UK Computer Misuse Act 1990.</p>
                            <p><strong className="text-white">3.2 Right to Audit.</strong> Zentinel does not verify authorization for every scan but reserves the right to request written proof of authorization at any time. Failure to provide such proof may result in immediate account termination and reporting to relevant authorities.</p>
                            <p><strong className="text-white">3.3 Indemnity for Unauthorized Use.</strong> You agree to fully indemnify Zentinel for any third-party claims arising from your testing of systems for which you lacked proper authorization.</p>
                        </div>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">04.</span> PROHIBITED CONDUCT
                        </h2>
                        <p>You shall not:</p>
                        <ul className="space-y-2 list-disc pl-5">
                            <li>Use the Service to facilitate cyberattacks, DDoS, or unauthorized data exfiltration.</li>
                            <li>Reverse engineer Zentinel’s autonomous agents or proprietary scanning logic.</li>
                            <li>Use the Service to test critical infrastructure (e.g., power grids, life-support systems) without Zentinel’s explicit written consent.</li>
                            <li>Resell or sublicense the Service to third parties without a formal Partner Agreement.</li>
                        </ul>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">05.</span> AI-DRIVEN REMEDIATION & PATCHES
                        </h2>
                        <div className="space-y-4">
                            <p><strong className="text-white">5.1 Nature of AI Recommendations.</strong> You acknowledge that Remediation Suggestions are generated by artificial intelligence. While Zentinel strives for accuracy, AI-generated code may contain errors, security regressions, or logic flaws.</p>
                            <p><strong className="text-white uppercase tracking-tighter">5.2 User Responsibility.</strong> YOU ARE SOLELY RESPONSIBLE FOR REVIEWING, TESTING, AND VALIDATING ANY REMEDIATION SUGGESTIONS OR PULL REQUESTS BEFORE MERGING THEM INTO YOUR PRODUCTION CODEBASE. Zentinel expressly disclaims all liability for system downtime, data loss, or new vulnerabilities introduced by your implementation of Remediation Suggestions.</p>
                        </div>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">06.</span> INTELLECTUAL PROPERTY & DATA RIGHTS
                        </h2>
                        <div className="space-y-4">
                            <p><strong className="text-white">6.1 Zentinel IP.</strong> Zentinel retains all rights, title, and interest in the Service, including its &quot;Memory & Learning&quot; algorithms and scanning methodologies.</p>
                            <p><strong className="text-white">6.2 User Data License.</strong> You grant Zentinel a limited license to process User Data solely to provide the Service to you.</p>
                            <p><strong className="text-white">6.3 Machine Learning & Improvement.</strong> Notwithstanding anything to the contrary, you grant Zentinel a perpetual, irrevocable, worldwide license to use De-identified and Aggregated Data (data that cannot be traced back to you or your specific Target Systems) to train our machine learning models, improve autonomous agent reasoning, and publish industry security benchmarks.</p>
                        </div>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">07.</span> DISCLAIMER OF WARRANTIES
                        </h2>
                        <p className="uppercase font-bold text-white text-xs tracking-wider">The service is provided &quot;as is.&quot; Zentinel does not warrant that:</p>
                        <ul className="space-y-2 list-none pl-0">
                            <li className="flex gap-3"><span className="text-[var(--color-cyan)]">•</span> <span>The service will identify every vulnerability.</span></li>
                            <li className="flex gap-3"><span className="text-[var(--color-cyan)]">•</span> <span>The service will be error-free or uninterrupted.</span></li>
                            <li className="flex gap-3"><span className="text-[var(--color-cyan)]">•</span> <span>Remediation suggestions are safe for production use.</span></li>
                            <li className="flex gap-3"><span className="text-[var(--color-cyan)]">•</span> <span>Security assessments are point-in-time and do not guarantee future immunity from attack.</span></li>
                        </ul>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">08.</span> LIMITATION OF LIABILITY
                        </h2>
                        <div className="space-y-4">
                            <p><strong className="text-white">8.1 Exclusion of Damages.</strong> TO THE MAXIMUM EXTENT PERMITTED BY LAW, ZENTINEL SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOSS OF PROFITS, DATA BREACH COSTS, OR REPUTATIONAL HARM.</p>
                            <p><strong className="text-white">8.2 Liability Cap.</strong> ZENTINEL’S TOTAL CUMULATIVE LIABILITY FOR ALL CLAIMS ARISING OUT OF THIS AGREEMENT SHALL NOT EXCEED THE TOTAL FEES PAID BY YOU TO ZENTINEL DURING THE TWELVE (12) MONTHS PRECEDING THE CLAIM.</p>
                        </div>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">09.</span> FEES AND PAYMENT
                        </h2>
                        <p>
                            Subscriptions are billed in advance. Annual plans are eligible for a pro-rated refund within the first 30 days only. Monthly plans are non-refundable. Failure to pay fees when due may result in immediate suspension of scanning capabilities.
                        </p>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">10.</span> GOVERNING LAW AND DISPUTE RESOLUTION
                        </h2>
                        <div className="space-y-4">
                            <p><strong className="text-white">10.1 Governing Law.</strong> This Agreement is governed by the laws of England and Wales, without regard to conflict of laws principles.</p>
                            <p><strong className="text-white">10.2 Jurisdiction.</strong> The courts of England and Wales shall have exclusive jurisdiction to settle any dispute or claim arising out of or in connection with this Agreement or its subject matter.</p>
                            <p><strong className="text-white">10.3 Class Action Waiver.</strong> TO THE EXTENT PERMITTED BY LAW, YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION.</p>
                        </div>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight flex items-center gap-3">
                            <span className="text-[var(--color-cyan)] font-mono text-sm leading-none">11.</span> TERMINATION
                        </h2>
                        <p>
                            Either party may terminate this Agreement upon notice. Upon termination, your right to access the dashboard and API ceases immediately. Zentinel will delete your User Data in accordance with our Privacy Policy after a 30-day grace period.
                        </p>
                    </section>

                    <section className="space-y-8 pt-12 border-t border-white/10">
                        <h2 className="text-xl font-syne font-bold text-white tracking-tight">
                            12. CONTACT & CORPORATE INFORMATION
                        </h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 font-mono text-xs uppercase tracking-widest leading-loose">
                            <div>
                                <p className="text-[#555] mb-2">Legal Notices</p>
                                <a href="mailto:legal@moyopal.io" className="text-white hover:text-[var(--color-cyan)] transition-colors">legal@moyopal.io</a>

                                <p className="text-[#555] mt-6 mb-2">Security/Disclosure</p>
                                <a href="mailto:legal@moyopal.io" className="text-white hover:text-[var(--color-cyan)] transition-colors">legal@moyopal.io</a>
                            </div>
                            <div>
                                <p className="text-[#555] mb-2">General Support</p>
                                <a href="mailto:alvin@moyopal.io" className="text-white hover:text-[var(--color-cyan)] transition-colors">alvin@moyopal.io</a>

                                <div className="mt-8 pt-8 border-t border-white/5 space-y-1">
                                    <p className="text-white">Moyopal Ltd</p>
                                    <p className="text-[#444]">Registered in England and Wales.</p>
                                    <p className="text-[#444]">Company Number: 16288400</p>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </main>
    );
}
